apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: gcp-secret-manager
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  type: secretstores.gcp.secretmanager
  version: v1
  metadata:
    - name: type
      value: service_account
    - name: project_id
      value: hdfc-qa-testing
    - name: private_key_id
      value: 70c7a56c6c83eba2cf0a71b2ab031ca389a5e95c
    - name: client_email
      value: dapr-sa@hdfc-qa-testing.iam.gserviceaccount.com
    - name: client_id
      value: 100027116060207381370
    - name: auth_uri
      value: https://accounts.google.com/o/oauth2/auth
    - name: token_uri
      value: https://oauth2.googleapis.com/token
    - name: auth_provider_x509_cert_url
      value: https://www.googleapis.com/oauth2/v1/certs
    - name: client_x509_cert_url
      value: https://www.googleapis.com/robot/v1/metadata/x509/dapr-sa%40hdfc-qa-testing.iam.gserviceaccount.com
    - name: private_key
      value: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvF6nRSnD+P1gO\n1tEhd3EDZ5q5Fxq8lTzR37KP/sUhkSBj8HgTOLZ9yMdqynA+PH1QWG+lqWZqWOcN\nNVkZl/qne8L/8w8BTR6UT03j7vr3Gtfc27pFLC4Y75aYO+1hSHX29upbZNaqVF7q\n2LdRUWYdBUEUyyPqT8A/e5Uedi3tOwSmjWF5n8NLG4OUiHVxOoww6TP69S7j4UyD\nkzPtBO2VDwi3Dijup1N3ybbBxeQxCGC4Ji3suQ1HC//FDV0eJp2VJviU42SpTX+t\nufC/x7pTUY8gOCf8//P2Xxj3FjuRUi4Cmtc0K+O4sdTOhLNVGVDoiJu3vZZev+LP\nalaxelv/AgMBAAECggEAVenxEDqMPh0b2tAqdtbyU77bCzYcjutVmA/BQOm8le9t\nqsw8RwY9eXPy8eIaeFdbDkM84cvM0CjQvZp3WaWeZ69PcxZiyOtCxDpnPFnkmE\nISGKAVYf2ml5hgJlxKX3CDL5JNZShOp4Vpj3PoYH6naBDDBvU5JFXYEI1xUbDPtn\nnP31Ov4KoDGI3wTwATLB2EYCKR6Vx9ae8OOcB0R8TUdqsADiJj6DQ5QsdrygrxJv\n+fj0nCt2KtuiI99+xYYycHZw0GG18A9rw7JCmpXvRQHqxenOtRrXOhq7UoOFiA5S\nFTC8XO7fPWdcIUPMbHcnne8zyVL5PlsMYeLKVWGkLQKBgQDmAqSNE86dzaZepDac\nnQala4y6mqAh77+vLr16NkGR9DPckQbsoDh/zfyq/npSyNQXSLcSwhI5sQQ3gVO0\nzkurJPQo3ZnJ4m23ii/2b/Pn23YJ702F4oZzU2D6jWZSksnTmGKSBIC4xwDPVZMB\njmsU6IuvzDxUxd9wvs1IvDdUUwKBgQDC4HJsNPmmcAGrCtKjDGyGwl5/J6Mmp98W\neJguV0PZVN9UCW+5XKI71XZqfktIM6ZiiFDrBMHyQrG0uYQyCK+QmTrABs/ZbB84\nDhejXXCr2s4UhuaTgw41OnCIQgcQlzv2zBFST++Y+fEsYUPme4mufuaZAPsq7BGm\nRLtJt/KkJQKBgAJj2qPgpc/7+BOZrzuXYh9L681wl+NiY2KFoNBpSesjV3qeQy0o\nSQ4C7PI17L15esK3LbfTLm9NCJcvD9icICsqGiNmkheH883pcLAl36n0HNjjlLGk\ndfMy1Zok6ABJqDE7ryKHS3MgFkERSZLFkRVJiVINVD8pQzYftXBhDE4jAoGBAKEc\nurynF3b4xwhHzFksnlTTQRjTBlmhFBkZ3ocBcoCtYG2z14BiC2Z4Vow4mbi5qudv\nV6bVqhrF9PE7JwXOlIdxh1bWyuQwNac8T2Kqj8ok/ZeO5/YwtYBgLkUYgYq3b1u\nfSuWFrpceX19dIuKuwtesvrwCrczsGvMCyMpRxtZAoGBAL23kkVMtpWMmAMfX85B\nDXboBfcAYHJsT9cPYV8KnCy7glkmJds4N0PXAFO5jfX0dwRtmK8obOdnz8Kbig\nNruczCFSFL5Htwk9DChO9K06+5McVSMKZu2mxlS3Vt08Wh9GIlkLPCez4Bbn3rE0\nudH15pTS2GBJx8T9U7cYUjK1\n-----END PRIVATE KEY-----\n"
